<a href="https://colab.research.google.com/github/brn1214/ITMO-Practices/blob/main/k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
import numpy
from sklearn.metrics import DistanceMetric

In [ ]:
from google.colab import drive
drive.mount('/drive/')

Mounted at /drive/


In [ ]:
data = pd.read_csv("/drive/MyDrive/itmo/colab/cluster.csv", encoding = 'utf-8', delimiter=',')

data2= data.drop('Object', axis=1)

In [ ]:
data2.head()

X   Y  Cluster
0   1  12        0
1  20   6        1
2  16   5        2
3   6  15        1
4   7   3        1

In [ ]:
X = data2.drop('Cluster', axis=1)
print(X)

     X   Y
0    1  12
1   20   6
2   16   5
3    6  15
4    7   3
5   19  15
6    5   4
7   18  15
8    3   6
9    3  18
10  20  17
11   1   8
12  20  10
13   8   9
14   8   3


In [ ]:
kmeans = KMeans(n_clusters=3, init=np.array([[7.5, 12.0], [11.43, 8.43], [11.25, 9.75]]), max_iter=100, n_init=1)
kmeans.fit(X)

KMeans(init=array([[ 7.5 , 12.  ],
       [11.43,  8.43],
       [11.25,  9.75]]),
       max_iter=100, n_clusters=3, n_init=1)

In [ ]:
y_kmeans = kmeans.predict(X)
print(y_kmeans)

[0 1 1 0 1 2 0 2 0 0 2 0 2 0 1]


In [ ]:
centers = kmeans.cluster_centers_
lab = kmeans.labels_
print(centers, lab)

[[ 3.85714286 10.28571429]
 [12.75        4.25      ]
 [19.25       14.25      ]] [0 1 1 0 1 2 0 2 0 0 2 0 2 0 1]


In [ ]:
a = [[3.85714286, 10.28571429], [1, 12]]
b = [[3.85714286, 10.28571429], [6, 15]]
c = [[3.85714286, 10.28571429], [5, 4]]
d = [[3.85714286, 10.28571429], [3, 6]]
e = [[3.85714286, 10.28571429], [3, 18]]
f = [[3.85714286, 10.28571429], [1, 8]]
g = [[3.85714286, 10.28571429], [8, 9]]


dist = DistanceMetric.get_metric('euclidean')
print(dist.pairwise(a))
print(dist.pairwise(b))
print(dist.pairwise(c))
print(dist.pairwise(d))
print(dist.pairwise(e))
print(dist.pairwise(f))
print(dist.pairwise(g))


[[0.         3.33197251]
 [3.33197251 0.        ]]
[[0.         5.17844827]
 [5.17844827 0.        ]]
[[0.         6.38876565]
 [6.38876565 0.        ]]
[[0.         4.37058816]
 [4.37058816 0.        ]]
[[0.         7.76175869]
 [7.76175869 0.        ]]
[[0.         3.65892814]
 [3.65892814 0.        ]]
[[0.         4.33777898]
 [4.33777898 0.        ]]


In [ ]:
prom = (3.33197251 + 5.17844827 + 6.38876565 + 4.37058816 +7.76175869 +3.65892814 + 4.33777898)/7
print(prom)

5.004034342857143
